### ISSUE TITLE
Attribute error in 'collection.create_partition' if create an existed partition

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/pymilvus-orm#200]
```python
>>> collection.create_partition("comedy", description="comedy films")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yangxuan/Github/pymilvus-orm/pymilvus_orm/collection.py", line 763, in create_partition
    raise PartitionAlreadyExistException(0, ExceptionsMessage.PartitionAlreayExist)
AttributeError: type object 'ExceptionsMessage' has no attribute 'PartitionAlreayExist'
```

pymilvus-orm == 2.0a1.dev59

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/222
