### ISSUE TITLE
SchemaNotReadyException will be thrown when insert INT16 data

### ISSUE THREAD

**Issue by czhen-zilliz** [milvus-io/pymilvus-orm#284]
**Env**:
    `Python 3.7.10`, `pymilvus-orm==2.0.0rc4`

**Description**:

When I create a collection with schema which has `DataType.INT16` field, it would fail if I try to insert int data.

**If I change the `DataType` from `INT16` to `INT64`, it work well.**
**It just failed when I set `INT16` or `INT32`(not test for any other types).**

Code below is my example:
Fields those would fail are `color` and `brand`.

```
>>> from pymilvus_orm import connections, Collection, FieldSchema, CollectionSchema, DataType
>>> import random
>>> connections.connect()
<pymilvus.client.stub.Milvus object at 0x10b39aa90>
>>> schema = CollectionSchema([
...     FieldSchema("id", DataType.INT64, is_primary=True),
...     FieldSchema("vector", dtype=DataType.FLOAT_VECTOR, dim=128),
...     FieldSchema("color", DataType.INT16),
...     FieldSchema("brand", DataType.INT16),
... ], auto_id=True)
>>> collection = Collection("car_test", schema)
>>> data = [
...     [[random.random() for _ in range(128)] for _ in range(10)],
...     [i for i in range(10)],
...     [i for i in range(10)],
... ]
>>> collection.insert(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/czhen/Desktop/milvus_cli/venv/lib/python3.7/site-packages/pymilvus_orm/collection.py", line 514, in insert
    raise SchemaNotReadyException(0, ExceptionsMessage.TypeOfDataAndSchemaInconsistent)
pymilvus_orm.exceptions.SchemaNotReadyException: <SchemaNotReadyException: (code=0, message=The types of schema and data do not match.)>
```

**Comment by XuanYang-cn** [comment]
Moved into pymilvus, closing
